Gemfile
Gem debugger does not support ruby 2+ as description says [here](https://github.com/cldwalker/debugger). So it makes sense to limit than for specific platforms.
=> use debugger gem only for old ruby versions

lib/hair_trigger/schema_dumper.rb, spec/schema_dumper_spec.rb
Hello!
There is an option on AR called ignore_table exists: http://apidock.com/rails/ActiveRecord/SchemaDumper/ignore_tables/class
Right now after setting this option tables you want to remove from your schema.rb dissapear, but if any of  those tables have triggers - they stay there.
This PR make SchemaDumper to take in consideration this option.
=> ActiveRecord::SchemaDumper.ignore_tables work on generating dumps

lib/hair_trigger.rb
I noticed that `hair_trigger` was requiring a lot of memory on startup. Using `derailed_benchmarks`
I tracked that down to the loading of the `ruby_parser` and `ruby2ruby` gems.
Since those libraries are only needed by the `HairTrigger::MigrationReader` it
is possible to use `autoload` to lazy-load those libraries only when needed.
In a sample case of a Gemfile that only includes `activerecord` and `hairtrigger`
the total memory allocated just to load the Gemfile dropped from 53MB to 23MB. At least 6MB of that memory is not able to be garbage collected. The observed process memory dropped from ~25MB to ~16MB.
Here is a process for recreating those performance results...
Create a `Gemfile.derailed` file in the project root directory
```ruby
source 'https://rubygems.org'
gem …
```
=> Lazy load dependencies to reduce memory on startup

lib/hair_trigger/builder.rb
Currently it outputs `all(nil)` which throws an argument error since it doesn't take arguments.
=> Ensure all() is not given any parameters when converted to ruby.

lib/hair_trigger/builder.rb
Allowing  `of()` from inside of a trigger group does not break anything in MySQL.  Tested on 5.6 and 5.7.
=> Allow of() in trigger group for MySQL.

Appraisals, Gemfile, gemfiles/activerecord_3.2.gemfile, gemfiles/activerecord_4.0.gemfile, gemfiles/activerecord_4.2.gemfile, gemfiles/activerecord_5.0.gemfile, gemfiles/activerecord_5.1.gemfile, gemfiles/activerecord_edge.gemfile
It was impossible to run tests on Travis CI due too loose requirements on gem versions. Bundler was loading version too new for specific Rails version.
I have copied required versions from `active_record/connection_adapters/*` for each adapter*.
----
(*) There was an issue with mysql2 0.4.3 and Rails 5.x so I kept `~> 0.4.4` version constraint.
=> Adjust adapter gem versions to required versions in Rails

lib/hair_trigger.rb
Thank you for this great product. 
- Ruby: 2.5.0
- Rails: 5.2.0
I met the error shown below when run `rails db:migrate`
```
NoMethodError: undefined method `migrations' for ActiveRecord::Migrator:Class
/app/myapp/vendor/bundle/ruby/2.5.0/gems/hairtrigger-0.2.20/lib/hair_trigger.rb:45:in `migrator'
/app/myapp/vendor/bundle/ruby/2.5.0/gems/hairtrigger-0.2.20/lib/hair_trigger.rb:65:in `current_migrations'
/app/myapp/vendor/bundle/ruby/2.5.0/gems/hairtrigger-0.2.20/lib/hair_trigger/schema_dumper.rb:23:in `triggers'
/app/myapp/vendor/bundle/ruby/2.5.0/gems/hairtrigger-0.2.20/lib/hair_trigger/schema_dumper.rb:7:in `trailer'
/app/myapp/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/schema_dumper.rb:39:in `dump'
/app/myapp/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/ac …
```
=> `ActiveRecord::Migrator.migrations` raises NoMethodError

lib/hair_trigger/builder.rb, spec/builder_spec.rb
Hey @jenseng,
I stumbled upon the error when defining triggers in file with `frozen_string_literals: true` comment. It turned out the builder is modifying SQL trigger body in place. I fixed it by using immutable modifications while ensuring semicolon presence.
WDYT?
=> Make builder work with frozen strings

lib/hair_trigger/builder.rb
This fixes issue #89 Ruby 2.7 gives warning on use of Proc.new:
`hair_trigger/builder.rb:145: warning: Capturing the given block using Proc.new is deprecated; use &blockinstead hair_trigger/builder.rb:155: warning: Capturing the given block using Proc.new is deprecated; use&block instead
`
=> Fix Ruby 2.7 warnings on Proc.new

lib/hair_trigger.rb
This PR addresses the problem of ActiveRecord::Base being called prior to a Rails apps own initializers being loaded. It manifested specifically in an inability to set `Rails.application.config.active_record.belongs_to_required_by_default = true` during our Rails 5 upgrade.
The fix is basically cribbing this fix right here: https://github.com/ankane/ahoy/issues/213 when the issue was seen in another gem.
=> Ensure hair_trigger ActiveRecord settings run after app load

lib/hair_trigger/schema_dumper.rb
I was getting `WARNING: generating adapter-specific definition` and `no candidate create_trigger statement could be found` when switching from the PostgreSQL to the PostGIS ActiveRecord adapter. This should fix that.
=> add postgis support to schema_dumper

README.md, lib/hair_trigger/schema_dumper.rb, spec/schema_dumper_spec.rb
There are other gems that handle adding or removing their triggers in the schema dump, so we don't always want to dump every trigger.
Instead, we allow specific triggers and tables to be allowed or ignored by configuration.
=> Add trigger filtering support to schema dumper

.github/workflows/workflow.yml, spec/spec_helper.rb
Also start using ruby/setup-ruby instead of actions/setup-ruby which is deprecated. This allows us to test with 3.0 but also  allows us to cache bundler between runs.
=> Add Ruby 3 to CI

.github/workflows/workflow.yml, gemfiles/activerecord_5.0.gemfile, gemfiles/activerecord_5.1.gemfile, gemfiles/activerecord_5.2.gemfile, gemfiles/activerecord_6.0.gemfile, gemfiles/activerecord_6.1.gemfile, gemfiles/activerecord_7.0.gemfile, gemfiles/activerecord_edge.gemfile, spec/spec_helper.rb
In addition to the necessary changes to the `workflow.yml` - added `3.1` and excluding unsupported ActiveRecord/Ruby combinations, the following changes were made:
1. Updated gemfiles to modern versions of rake and rspec - this was necessary to get specs running.  There are some deprecation warnings, but everything runs green
2. Use YAML safe_load with an aliases true argument - As Psych 4.0+ now calls `safe_load` for `load`, we make this call explicit and add the necessary aliases argument for it to pass.
=> Add Ruby 3.1 to the CI matrix

lib/hair_trigger.rb
Rails 7's schema.rb looks similar to `ActiveRecord::Schema[7.0].define(version: 2022_01_26_205052)` which breaks how the regex works, causing `assert HairTrigger::migrations_current?` to fail. This PR fixes that.
=> Update previous_schema regex to account for Rails 7

lib/tasks/hair_trigger.rake
Fix for https://github.com/jenseng/hair_trigger/issues/93.
Behavior stays the same as it was for Rails 5 and above.
As it's said in the issue, we don't need to generate a `schema.rb` when we don't have the setting `schema_format = :ruby`.
=> Skip schema.rb when schema_format is set to :sql

lib/hair_trigger.rb, lib/hair_trigger/adapter.rb
We stumbled upon a app, that uses another Postgres schema by default. In that case ``rails db:schema:dump`` will not include the triggers by HairTrigger.
This PR makes the schema configurable and will keep `public` as default.
=> Feat: support Postgres schema config setting

Appraisals, CHANGELOG.md, gemfiles/activerecord_6.0.gemfile, gemfiles/activerecord_6.1.gemfile, gemfiles/activerecord_7.0.gemfile, lib/hair_trigger/adapter.rb, lib/hair_trigger/builder.rb, spec/adapter_spec.rb
Add support for trilogy adapter 
https://github.com/trilogy-libraries/trilogy
https://github.com/trilogy-libraries/activerecord-trilogy-adapter
Trilogy adapter is now supported as a native mysql adapter in Rails 7.1
=> Support trilogy as mysql adapter

CHANGELOG.md, lib/tasks/hair_trigger.rake
Fix following issue(#95). This is the rebase from pull request #98.
**Background:**
We are trying to set up multiple databases with our **Rails 7** application. Due to this gem, we are facing an issue.
When we are running **rails db:migrate**
it is overwriting the primary **db/schema.rb** file with secondary schema file **db/marketing_sync_board_schema.rb**. After the migration command run both are the same. 
They are not causing any database label changes.
Also if we are using database-specific command it is working fine. 
`rails db:migrate`
`rails db:migrate:marketing_sync_board`
sample database.yml with multi database setup.
<pre>
default: &default
adapter: postgresql
encoding: unicode
host: localhost
database: multi_db_test_app_development
username: admin
password:
pool: <%= …
=> [FIX]  fix migration issue for multiple database support(issue #95)

Appraisals
This looks like a simple copy/paste issue, with this change the gem should be tested against the correct `activerecord` version.
=> Appaisals: really test against ActiveRecord 7.1.x

README.md, lib/hair_trigger/builder.rb, spec/builder_spec.rb
fix: https://github.com/jenseng/hair_trigger/issues/123
add ability to access to transition tables. that allow to know which rows changed, this is especially useful when using statement triggers
=> Refactor HairTrigger builder to support referencing old and new tables

lib/hair_trigger.rb, lib/hair_trigger/adapter.rb, lib/hair_trigger/builder.rb, lib/hair_trigger/configuration.rb, lib/hair_trigger/schema_dumper.rb
The list of supported adapters is hardcoded, which makes it difficult to use this gem on custom adapters.
We use `postgresql_proxy` from `active_record_proxy_adapters`, for instance. Currently, we need to monkey patch the gem and hot swap the constant `HairTrigger::POSTGRESQL_ADAPTERS`  when the application boots to make it work with the proxy adapter.
Although it works, it's not ideal.
I've added a new configuration class whose values will default to the current ones (`%i[mysql2 trilogy]` for `mysql_adapters`, `%i[postgresql postgis]` for `postgresql_adapters` , and `%i[sqlite litedb]` for `sqlite_adapters`), but allow the user to add custom adapters for each.
I don't expect any breaking changes here as the values fall back to the existing constants, but please double check. Thanks!
=> Add configuration class for custom adapters
